#!/bin/bash
# Script to copy FRIB lattice element field description files from Dropbox archive to the simulation directory. This shell executable script should be extended and run as necessary when field element data changes and/or simulations are being carried out on a new platform. Execute with:
# % ./frib-lat-fields-dropbox-fetch
#
# See information in Dropbox for the field element descriptions and data sets.   

# Make various lattice element directories if not present to store field element data
mkdir -p lat_d5 lat_ecr_venus lat_gag lat_q7 lat_s4 

# Fetch lattice field files from Dropbox repo in the relevant directories.  Note that -nc for no clobber option 
# is being used. I don't understand why, but the dropbox time stamp of the file is not transmitted correctly 
# (always present system time).  nc appears to be wrt name.  So if the same file name (date in name) is retransmitted, 
# this may cause a problem. Unsure how to fix this. But -nc makes fast if file is there (gets skipped).  
# -- d5 dipole
cd lat_d5 
wget -nc https://www.dropbox.com/s/ijs2s6jnux3fzzi/bend_trans.table
wget -nc https://www.dropbox.com/s/824irj3jwvm94fb/lat_d5.3d.20140527.pkl
cd .. 
# -- ecr venus 
cd lat_ecr_venus 
wget -nc https://www.dropbox.com/s/5x7zyex1q5552xs/lat_ecr_venus.lin.20140602.pkl
wget -nc https://www.dropbox.com/s/2pjh15etmt5ky87/lat_ecr_venus.lin.20160218.pkl
cd ..
# -- grated acceleration gap 
cd lat_gag 
wget -nc https://www.dropbox.com/s/rwppvhlmtc38n3y/lat_gag.lin.20141029.pkl
wget -nc https://www.dropbox.com/s/42fgtl05y8u9uco/lat_gag.rz.20141029.pkl
cd .. 
# -- q7 quadrupole 
cd lat_q7 
wget -nc https://www.dropbox.com/s/xs5cqttfmbq1nee/lat_q7.3d.20160607.pkl
cd .. 
# -- s4 solenoid 
cd lat_s4 
wget -nc https://www.dropbox.com/s/fj4zjqsa2v6gsca/lat_s4.at.20141031.pkl
wget -nc https://www.dropbox.com/s/i7setjqpgozrars/lat_s4.lin.20141031.pkl
wget -nc https://www.dropbox.com/s/itliy3ev8zxd84r/lat_s4.rz.20141031.pkl
cd ..


